{
  "uid" : "74ec87ffc21a6870",
  "name" : "test_03",
  "fullName" : "Moneybox.tests.Get_all_moneybox.test_is_archived_field.TestGetAll#test_03",
  "historyId" : "b69a38bb015627869e96c4ce0eb7eaa3",
  "time" : {
    "start" : 1740069390761,
    "stop" : 1740069390761,
    "duration" : 0
  },
  "description" : "Неверный тип данных",
  "descriptionHtml" : "<p>Неверный тип данных</p>\n",
  "status" : "failed",
  "statusMessage" : "AssertionError: Ошибка {\"errors\":{\"status\":404,\"detail\":\"User does not exist\"}}",
  "statusTrace" : "@pytest.fixture()\n    def auth_fixture():\n        result = Auth.auth()\n>       Checking.check_statuscode(result, 200)\n\nconftest.py:21: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nresult = <Response [404]>, status_code = 200\n\n    @staticmethod\n    def check_statuscode(result, status_code):\n        with allure.step('Проверка статус кода'):\n>           assert result.status_code == status_code, f\"Ошибка {result.text}\"\nE           AssertionError: Ошибка {\"errors\":{\"status\":404,\"detail\":\"User does not exist\"}}\n\ncommon_methods/checking.py:13: AssertionError",
  "flaky" : false,
  "newFailed" : false,
  "beforeStages" : [ {
    "name" : "_session_faker",
    "time" : {
      "start" : 1740069370342,
      "stop" : 1740069370651,
      "duration" : 309
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "stepsCount" : 0,
    "hasContent" : false
  }, {
    "name" : "auth_fixture",
    "time" : {
      "start" : 1740069390762,
      "stop" : 1740069393055,
      "duration" : 2293
    },
    "status" : "failed",
    "statusMessage" : "AssertionError: Ошибка {\"errors\":{\"status\":404,\"detail\":\"User does not exist\"}}\n",
    "statusTrace" : "  File \"/usr/local/lib/python3.12/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/usr/local/lib/python3.12/site-packages/_pytest/setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"/usr/local/lib/python3.12/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.12/site-packages/_pytest/fixtures.py\", line 1139, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.12/site-packages/_pytest/fixtures.py\", line 897, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n                     ^^^^^^^^^^^^^^^^^^^^^\n  File \"/Budget_api/conftest.py\", line 21, in auth_fixture\n    Checking.check_statuscode(result, 200)\n  File \"/Budget_api/common_methods/checking.py\", line 13, in check_statuscode\n    assert result.status_code == status_code, f\"Ошибка {result.text}\"\n",
    "steps" : [ {
      "name" : "Авторизация",
      "time" : {
        "start" : 1740069390762,
        "stop" : 1740069393055,
        "duration" : 2293
      },
      "status" : "passed",
      "steps" : [ ],
      "attachments" : [ ],
      "parameters" : [ ],
      "attachmentsCount" : 0,
      "shouldDisplayMessage" : false,
      "stepsCount" : 0,
      "hasContent" : false
    }, {
      "name" : "Проверка статус кода",
      "time" : {
        "start" : 1740069393055,
        "stop" : 1740069393055,
        "duration" : 0
      },
      "status" : "failed",
      "statusMessage" : "AssertionError: Ошибка {\"errors\":{\"status\":404,\"detail\":\"User does not exist\"}}\n",
      "statusTrace" : "  File \"/Budget_api/common_methods/checking.py\", line 13, in check_statuscode\n    assert result.status_code == status_code, f\"Ошибка {result.text}\"\n",
      "steps" : [ ],
      "attachments" : [ ],
      "parameters" : [ ],
      "attachmentsCount" : 0,
      "shouldDisplayMessage" : true,
      "stepsCount" : 0,
      "hasContent" : true
    } ],
    "attachments" : [ ],
    "parameters" : [ ],
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "stepsCount" : 2,
    "hasContent" : true
  } ],
  "afterStages" : [ ],
  "labels" : [ {
    "name" : "epic",
    "value" : "GET /api/v1/moneybox/ Проверка поля is_archived"
  }, {
    "name" : "tag",
    "value" : "Moneybox"
  }, {
    "name" : "tag",
    "value" : "get_moneybox"
  }, {
    "name" : "parentSuite",
    "value" : "Moneybox.tests.Get_all_moneybox"
  }, {
    "name" : "suite",
    "value" : "test_is_archived_field"
  }, {
    "name" : "subSuite",
    "value" : "TestGetAll"
  }, {
    "name" : "host",
    "value" : "eeeb0889f130"
  }, {
    "name" : "thread",
    "value" : "1-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "Moneybox.tests.Get_all_moneybox.test_is_archived_field"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "normal",
    "retries" : [ ],
    "categories" : [ {
      "name" : "Product defects",
      "matchedStatuses" : [ ],
      "flaky" : false
    } ],
    "tags" : [ "Moneybox", "get_moneybox" ]
  },
  "source" : "74ec87ffc21a6870.json",
  "parameterValues" : [ ]
}